export const MOCKUSSTATESDATA = [
  "Alaska",
  "Alabama",
  "Arkansas",
  "California",
  "District of Columbia",
  "Delware",
  "Kentucky",
  "New Hampshire",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oregon",
  "South Dakota",
  "Washington",
  "Wyoming",
  "West Virginia",
  "Virginia",
  "Vermont",
];
